# Generated by Django 6.0.6 on 2026-07-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
                ('des', models.TextField()),
                ('created_at', models.DateField()),
                ('update_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FileActivityLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('timestamp', models.DateField()),
                ('old_file', models.CharField(blank=True, max_length=255, null=True)),
                ('new_file', models.CharField(blank=True, max_length=255, null=True)),
                ('old_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('new_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('file_path', models.CharField(max_length=100)),
                ('uploaded_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.doccategory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
    ]
