# Generated by Django 6.0.6 on 2026-07-08 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doccategory',
            options={'verbose_name_plural': 'Document Categories'},
        ),
        migrations.AlterModelOptions(
            name='fileactivitylogs',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'File Activity Logs'},
        ),
        migrations.RenameField(
            model_name='doccategory',
            old_name='des',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='doccategory',
            name='update_at',
        ),
        migrations.AddField(
            model_name='doccategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fileactivitylogs',
            name='name_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='role_status',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'User'), ('viewer', 'Viewer')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='doccategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='documents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fileactivitylogs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
