# Generated by Django 6.0.6 on 2026-07-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doccategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='documents',
            name='document_number',
            field=models.CharField(blank=True, help_text='Optional: ID number, passport number, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='When does this document expire?', null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='issue_date',
            field=models.DateField(blank=True, help_text='When was this document issued?', null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('archived', 'Archived')], default='valid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='documents',
            index=models.Index(fields=['user', 'status'], name='accounts_do_user_id_bf5ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='documents',
            index=models.Index(fields=['expiration_date'], name='accounts_do_expirat_a021b4_idx'),
        ),
    ]
